server:
  port: 9099

#JDBC Oracle Connection
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger

# MyBatis
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.wishiext.wishiext.vo
  type-handlers-package: com.wishiext.wishiext.dao